[package]
name = "database_exporting"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
users = "0.11.0"
time = { version = "0.3.20", features = ["std", "formatting", "parsing"] }
dotenvy = "*"

